export const JITSI_SETTINGS = {
  DOMAIN: 'meet.banter.network',
  CONFIG: {
    MODERATOR: {
      hideConferenceTimer: true,
      doNotStoreRoom: true,
      startWithAudioMuted: false,
      apiLogLevels: ['error'],
      transcribingEnabled: false,
      disableThirdPartyRequests: false,
      // enableSaveLogs: false,
      // hideParticipantsStats: true,
      hideConferenceSubject: true,
      enableDisplayNameInStats: true,
      enableEmailInStats: true,
      disableFilmstripAutohiding: false,
      // disable1On1Mode: null,
      disableShowMoreStats: true,
      toolbarButtons: [
        'microphone',
        'camera',
        'closedcaptions', // -->> start/stop subtitles
        'desktop',
        'embedmeeting',
        'fullscreen',
        'fodeviceselection',
        'hangup',
        // 'profile',
        'chat',
        'etherpad',
        'settings',
        'raisehand',
        'videoquality',
        // 'filmstrip',
        // 'stats',
        'shortcuts',
        'tileview',
        'mute-everyone',
        'select-background',
        // 'invite',
        'toggle-camera',

        // 'feedback',
        'mute-video-everyone',
        'participants-pane',
        // 'profile',
        // 'security',
        // 'shareaudio',
        // 'sharedvideo',
        // '__end', // ? not found
      ],
      disablePolls: true,
    },
    GUEST: {
      hideConferenceTimer: true,
      doNotStoreRoom: true,
      startWithAudioMuted: false,
      apiLogLevels: ['error'],
      transcribingEnabled: false,
      disableThirdPartyRequests: false,
      // callStatsCustomScriptUrl: "https://api.callstats.io/static/callstats.min.js"
      // enableSaveLogs: false,
      // hideParticipantsStats: true,
      hideConferenceSubject: true,
      enableDisplayNameInStats: true,
      enableEmailInStats: true,
      disableFilmstripAutohiding: false,
      // disable1On1Mode: null,
      disableShowMoreStats: true,
      toolbarButtons: [
        'microphone',
        'camera',
        'closedcaptions', // -->> start/stop subtitles
        'desktop',
        'embedmeeting',
        'fullscreen',
        'fodeviceselection',
        'hangup',
        // 'profile',
        'chat',
        // 'recording',
        // 'livestreaming',
        'etherpad',
        'settings',
        'raisehand',
        'videoquality',
        // 'filmstrip',
        // 'stats',
        'shortcuts',
        'tileview',
        'select-background',
        'toggle-camera',
        'participants-pane',
      ],
      disablePolls: true,
    },
  },
  INTERFACE_CONFIG: {
    MODERATOR: {
      TOOLBAR_ALWAYS_VISIBLE: false,
      ENABLE_DIAL_OUT: true,
      DISABLE_TRANSCRIPTION_SUBTITLES: false,
      SUPPORT_URL: '',
      VIDEO_QUALITY_LABEL_DISABLED: true,
    },
    GUEST: {
      TOOLBAR_ALWAYS_VISIBLE: false,
      ENABLE_DIAL_OUT: true,
      DISABLE_TRANSCRIPTION_SUBTITLES: false,
      SUPPORT_URL: '',
      VIDEO_QUALITY_LABEL_DISABLED: true,
    }
  }
};
